### PR TITLE
Update README and Dockerfile

### PR DESCRIPTION
**Pull request by shrmrf**
Dear concerned,

First of all, thank you for creating this repository. I was looking and trying out the sources and the things that tripped me are fixed in this PR:

- Use ubuntu:18.04 instead of debian:latest (because we are trying to install the `linux-headers-$(uname -r)` package which isn't available in debian apparently
- Use `apt-get` instead of `apt` (`apt` cli may change)
- Consolidate all `apt-get install` statements (less layers)
- Instead of the kaist mirror, use GitHub's mirror of DPDK (I don't know whether you like it this way or not)
- Update README.md

### CODE REVIEW

**Comment by leeopop** [comment]
Thank you for your pull request. We have several reasons to your concerns that we cannot merge your pull requests directly.

1. Single apt install statement vs multiple apt install statements
  We want other users to easily modify our source code to fit their specific environment so that we want to modularize the install statements into their purpose.
1. About using specific mirror
 DPDK and rust-bindgen are extreamly unstable, so that our solution only works with specific combination of their versions. We will soon change the mirror with specific version tags.
1. About Linux distribution
  Our infrastructure uses debian stable for preference. As our dockerfile is modular, it would be easy to make one's custom dockerfile for one's own preference.
1. apt vs apt-get
  Ubuntu and Debian suggest to make apt-get as legacy and apt as the new package infrastructure. We would like to participate their movement so we would like to keep apt as our default install command.

Thanks again for participating this repository.

**Comment by shrmrf** [comment]
@leeopop aah, sure... your responses make a lot of sense. Can you say which version of DPDK you're using right now? I checked out `18.11` (LTS) version.

3. I don't disagree with the usage of Debian. But I don't think the `linux-headers-<version>` package exists for debian. (I couldn't find it) let's either change the package, or use Ubuntu??

feel free to close the issue!!

**Comment by leeopop** [comment]
About the kernel packages: Debian (9 and 10) has kernel header packages (see our build log).
However, if current up-to-date header package differs from current running kernel image (e.g. when the system is not rebooted after the package upgrade), our dockerfile may not find the image.

I applied some of your suggestions into master branch. I'll close this PR, and if further changes are required, please create an issue for it.

**Comment by shrmrf** [comment]
Hi @leeopop thanks for the changes!!

**Pull request closed without merging**
